### ISSUE TITLE
Icon Request: Sleet

### ISSUE THREAD

**Issue by doxsch** [basmilius/weather-icons#1]
Hi Bas
I like your icons a lot and I appreciate your work very much. Currently I would like to use your icons in a side project. I need to be able to cover the following types (see picture below). Unfortunately I noticed that I am missing an icon. It would be great if you could create an icon for snow rain (sleet). In addition, you could possibly also distinguish fog and low stratus.

Thank you and best regards
doxsch
![image](https://user-images.githubusercontent.com/28098153/110853599-18661700-82b4-11eb-9def-11ab1d6e1804.png)

**Comment by basmilius** [comment]
Hi @doxsch

Thanks for liking my icons!  I'll try to make a sleet icon in the coming days and will look into fog a bit later. :)

**Comment by basmilius** [comment]
Hi! I've added a few new icons:

<table>
<tr><td>Sleet</td><td><img src="https://basmilius.github.io/weather-icons/production/line/all/sleet.svg" alt="sleet" height="64"/></td></tr>
<tr><td>Partly cloudy sleet (day)</td><td><img src="https://basmilius.github.io/weather-icons/production/line/all/partly-cloudy-day-sleet.svg" alt="partly-cloudy-day-sleet" height="64"/></td></tr>
<tr><td>Partly cloudy sleet (night)</td><td><img src="https://basmilius.github.io/weather-icons/production/line/all/partly-cloudy-night-sleet.svg" alt="partly-cloudy-night-sleet" height="64"/></td></tr>
</table>

I'm also still experimenting with fog:
<table>
<tr><td>Fog</td><td><img src="https://basmilius.github.io/weather-icons/production/line/all/fog.svg" alt="fog" height="64"/></td></tr>
<tr><td>Fog (day)</td><td><img src="https://basmilius.github.io/weather-icons/production/line/all/fog-day.svg" alt="fog-day" height="64"/></td></tr>
<tr><td>Fog (night)</td><td><img src="https://basmilius.github.io/weather-icons/production/line/all/fog-night.svg" alt="fog-night" height="64"/></td></tr>
<tr><td>Partly cloudy fog (day)</td><td><img src="https://basmilius.github.io/weather-icons/production/line/all/partly-cloudy-day-fog.svg" alt="partly-cloudy-day-fog" height="64"/></td></tr>
<tr><td>Partly cloudy fog (night)</td><td><img src="https://basmilius.github.io/weather-icons/production/line/all/partly-cloudy-night-fog.svg" alt="partly-cloudy-night-fog" height="64"/></td></tr>
</table>

**Comment by doxsch** [comment]
Hi @basmilius 

Many thanks for the new icons, they look great! 🤩
I am looking forward to use your icons.

best regards
