### ISSUE TITLE
Missing mostly sunny icon

### ISSUE THREAD

**Issue by poblabs** [basmilius/weather-icons#18]
Hi, this is a great set of weather icons! I noticed one is missing, and that is mostly sunny. Something like a large sun with a small cloud. 

![image](https://user-images.githubusercontent.com/3484775/178525307-e74414a1-9884-46c0-890f-312d6b061c2e.png)

**Comment by basmilius** [comment]
Hi! Thanks!

I'm actually working on a mostly sunny set of the icons, which can be found here: https://github.com/basmilius/weather-icons/issues/10#issuecomment-1128024095

Next week I finally have time to work on them again :)

**Comment by dtalens** [comment]
Ei @basmilius 
Were you able to finish mostly sunny icons?

**Comment by basmilius** [comment]
At that point, no haha... The upcoming v3 release will have a "mostly clear" variant of the icons. V3 will be released in the upcoming weeks.
