### ISSUE TITLE
ZIP download on https://bas.dev/work/meteocons does not include new icons

### ISSUE THREAD

**Issue by anthonyisensee** [basmilius/weather-icons#19]
@basmilius wanted to let you know that the zip download link from your website doesn't include some of the newer icons. For instance, code-red.svg. I was able to chase them down on this repo but just wanted to let you know.

I absolutely love what you've done with these icons. Thanks for releasing them to the interwebs!

**Comment by basmilius** [comment]
Hi!

Thanks for letting me know, I'll look into that soon.
