### ISSUE TITLE
Icon Request: High and Low

### ISSUE THREAD

**Issue by FatSandwich** [basmilius/weather-icons#2]
Is there a possibility for you to make high and low icons? I've been making a weather website and the only icons that are missing we're the high and low icons. Maybe just an arrow pointing up that's moving up and down, and vice versa. I couldn't find any icons like yours. Your icons are amazing! Thanks!

**Comment by basmilius** [comment]
Hi @FatSandwich, thanks for liking my icons!

I'll make these in the coming days. Your suggestion seems like the way to go, maybe i'll add two other variants with H and L 😃

**Comment by FatSandwich** [comment]
Thanks so much!

**Comment by basmilius** [comment]
How about this? 🤔 I have no animation for the letter variants.

https://user-images.githubusercontent.com/978257/112833091-85402600-9096-11eb-9aee-b8e8099d7b37.mov

**Comment by FatSandwich** [comment]
It looks so good! 🔥🔥🔥

**Comment by basmilius** [comment]
Thanks, they're tagged in the 1.5 release 😃

**Comment by FatSandwich** [comment]
Thanks!
