### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by elhamest** [basmilius/weather-icons#29]
hi, 
I used the npm package but couldn't use it in React project. 
please write a sample of usage. 
thank you.

**Comment by jsproton** [comment]
Hey did you ever figure out to how use these in react?

**Comment by basmilius** [comment]
Hi, sorry for the late reply. I'm looking into making both React and Vue components for the V3 release. You may however link to the icons directly using the following link structure:

`https://bmcdn.nl/assets/weather-icons/v2.0/[style]/[icon].svg`

Example: https://bmcdn.nl/assets/weather-icons/v2.0/fill/overcast-day.svg
