### ISSUE TITLE
Humidity, haze, dust, smoke Icons

### ISSUE THREAD

**Issue by B1gG** [basmilius/weather-icons#3]
Hi @basmilius
Have you is there any chance to add:
- a humidity icon? like the raindrop you have with the percentage inside and some kind of animation.
- Haze icon
- Dust icon
- Smoke icon
- also something for sprinkle, like 2 drops falling. 

Thanks for your help.

**Comment by B1gG** [comment]
This is to map the status from Weatherbits :), I will be using this in the MagicMirror project.
Of course all credit to you :)

**Comment by basmilius** [comment]
Hi!

I'll look into this in the coming days. Currently i'm on a little trip, so it might be a bit later 😀

**Comment by B1gG** [comment]
Enjoy, have a good weekend.
Thanks in advance

**Comment by basmilius** [comment]
I'm back and created these icons.. I'm not sure about the smoke particles and what kind of animation I should make for the humidity icon (and by extension the raindrop and raindrops icons).

Any feedback? :)

https://user-images.githubusercontent.com/978257/116881373-7b748a00-ac23-11eb-9530-9578222d59b5.mov

**Comment by B1gG** [comment]
Those icons look awesome :) I think that just like that is perfect.
For the humidity, as it is a kind of spot measure, it can remain just static (don't you think), for the raindrop it could be falling drops.

**Comment by basmilius** [comment]
Thanks! I just released [2.0](https://github.com/basmilius/weather-icons/releases/tag/v2.0.0) with these icons :)
