### ISSUE TITLE
Missing Mostly Sunny/Fair Icon

### ISSUE THREAD

**Issue by JesseLikesWeatherakaYoshiKart** [basmilius/weather-icons#35]
Hello @basmilius, I would like to note a missing icon, "Fair/Mostly Sunny."
 I think it would look like this: <img src="https://www.ibm.com/docs/en/SSRQLT_suite/images/Fair_mostly_sunny.png"></img *I don't know if the image is implemented..
  -JesseLikesWeather

**Comment by schinddo** [comment]
I have done it by myself by mixing existing SVGs together. Maybe you can use them.

mostly-clear-day.svg
`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 512 512">
  <defs>
    <symbol id="c" viewBox="0 0 292 292">
      <circle cx="146" cy="146" r="64.4" stroke="#f8af18" stroke-miterlimit="10" stroke-width="4" fill="url(#a)"/>
      <path d="M146 46.07V8m0 276v-38.07m70.66-170.59 26.92-26.92M48.42 243.58l26.92-26.92m0-141.32L48.42 48.42m195.16 195.16-26.92-26.92M46.07 146H8m276 0h-38.07" fill="none" stroke="#fbbf24" stroke-linecap="round" stroke-miterlimit="10" stroke-width="16">
		<animateTransform attributeName="transform" additive="sum" type="rotate" values="0 146 146; 45 146 146" dur="6s" repeatCount="indefinite"/>
	  </path>
    </symbol>
    <symbol id="d" viewBox="0 0 246 154">
      <path d="M204.6 74.22c-.6 0-1.18.06-1.77.09a57.58 57.58 0 0 0 1.77-14C204.6 28.12 178.15 2 145.51 2a59.17 59.17 0 0 0-50.23 27.72 39.52 39.52 0 0 0-20.12-5.5c-21.75 0-39.39 17.41-39.39 38.89a38.65 38.65 0 0 0 .56 6.31A41.8 41.8 0 0 0 2 110.33C2 133.35 20.9 152 44.21 152c.95 0 1.88-.08 2.81-.14v.14H204.6c21.76 0 39.4-17.41 39.4-38.89s-17.64-38.89-39.4-38.89Z" stroke="#e6effc" stroke-miterlimit="10" stroke-width="4" fill="url(#b)"/>
    </symbol>
    <symbol id="e" viewBox="0 0 379.59 291.6">
      <use width="292" height="292" xlink:href="#c"/>
      <use width="246" height="154" transform="translate(133.59 120.03)" xlink:href="#d"/>
    </symbol>
    <linearGradient id="b" x1="70.32" y1="20.85" x2="163.35" y2="181.99" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#f3f7fe"/>
      <stop offset="1" stop-color="#e6effc"/>
    </linearGradient>
    <linearGradient id="a" x1="113.79" y1="90.22" x2="178.21" y2="201.78" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#fbbf24"/>
      <stop offset="1" stop-color="#f8af18"/>
    </linearGradient>
  </defs>
  <use width="379.59" height="291.6" transform="translate(50.41 90.97)" xlink:href="#e"/>
</svg>
`

mostly-clear-night.svg
`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 512 512">
  <defs>
    <symbol id="c" viewBox="0 0 192 192">
      <path d="M160.62 107.4c-47.17 0-85.41-37.73-85.41-84.26A83.31 83.31 0 0 1 78 2C35.27 6.61 2 42.33 2 85.73 2 132.27 40.24 170 87.41 170A85.16 85.16 0 0 0 170 106.87a88 88 0 0 1-9.38.53Z" stroke="#72b9d5" stroke-linecap="round" stroke-linejoin="round" stroke-width="4" fill="url(#a)">
		<animateTransform attributeName="transform" additive="sum" type="rotate" values="-15 86 86; 9 86 86; -15 86 86" dur="10s" repeatCount="indefinite"/>
	  </path>	
	</symbol>
    <symbol id="d" viewBox="0 0 246 154">
      <path d="M204.6 74.22c-.6 0-1.18.06-1.77.09a57.58 57.58 0 0 0 1.77-14C204.6 28.12 178.15 2 145.51 2a59.17 59.17 0 0 0-50.23 27.72 39.52 39.52 0 0 0-20.12-5.5c-21.75 0-39.39 17.41-39.39 38.89a38.65 38.65 0 0 0 .56 6.31A41.8 41.8 0 0 0 2 110.33C2 133.35 20.9 152 44.21 152c.95 0 1.88-.08 2.81-.14v.14H204.6c21.76 0 39.4-17.41 39.4-38.89s-17.64-38.89-39.4-38.89Z" stroke="#e6effc" stroke-miterlimit="10" stroke-width="4" fill="url(#b)"/>
    </symbol>
    <symbol id="e" viewBox="0 0 329.96 224.6">
      <use width="192" height="192" xlink:href="#c"/>
      <use width="246" height="154" transform="translate(83.96 70.6)" xlink:href="#d"/>
    </symbol>
    <linearGradient id="b" x1="70.32" y1="20.85" x2="163.35" y2="181.99" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#f3f7fe"/>
      <stop offset="1" stop-color="#e6effc"/>
    </linearGradient>
    <linearGradient id="a" x1="38.56" y1="20.53" x2="133.16" y2="184.39" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#86c3db"/>
      <stop offset="1" stop-color="#72b9d5"/>
    </linearGradient>
  </defs>
  <use width="329.96" height="224.6" transform="translate(100.04 140.4)" xlink:href="#e"/>
</svg>
`
