### ISSUE TITLE
Add "exceptional" weather icon

### ISSUE THREAD

**Issue by rileytb** [basmilius/weather-icons#38]
For reference I am using Accuweather in Home Assistant and the [https://github.com/pkissling/clock-weather-card](https://github.com/pkissling/clock-weather-card) integration which uses the icons from this repo to represent the weather. 

However, when Accuweather shows the daily forecast as "exceptional" you can see here that it uses a circle with an exclamation point inside:

![image](https://github.com/basmilius/weather-icons/assets/5489576/5dacb564-f7bf-4695-a920-cf89d0025051)

The maintainer for the clock-weather-card widget has been using the hurricane/vortex icon as they were not able to find a suitable substitute for "exceptional" weather. (a [related issue](https://github.com/pkissling/clock-weather-card/issues/49))

I know that this might not be directly weather related, but could we get some sort of "exceptional weather" icon added for these scenarios?

**Comment by tykeal** [comment]
Duplicate of https://github.com/basmilius/weather-icons/issues/21

**Comment by rileytb** [comment]
Oh nuts, I looked for something similar but apparently I missed that. Sorry!
