### ISSUE TITLE
Icon Request: High Tide, Low Tide and Water Temperature

### ISSUE THREAD

**Issue by christopherdopp** [basmilius/weather-icons#6]
I just found your weather-icons repo and wanted to say thanks for creating a really nice set of icons. 

I have a suggestion for a few icons that technically are not weather, but could be considered just as important if you live near the ocean. I would love for you to create animated icons for:
* High Tide
* Low Tide
* Water Temperature

In my case I have a dashboard showing the next tide event and corresponding time. For example a High Tide icon with 7:21pm underneath it to indicate the next tide is High Tide which will occur at the specified time. Likewise a Water Temperature Icon with 60.4°F under it. 

I'm currently using static line icons and would love to have nicely animated ones. I'm attaching the icons I'm using for your reference. I don't know if you would consider creating animated versions, but I think multiple people would find them useful.

![high_tide](https://user-images.githubusercontent.com/12258633/120706079-a81bfb80-c486-11eb-89d1-b58a36c975a7.png)
![low_tide](https://user-images.githubusercontent.com/12258633/120706087-aa7e5580-c486-11eb-9e63-db940a34c08f.png)
![water_temp](https://user-images.githubusercontent.com/12258633/120706093-ad794600-c486-11eb-8c97-92b4e283c9fb.png)

**Comment by basmilius** [comment]
Hi! Thanks for liking my icons :)

I do like the requested icons, I will try to design them maybe tomorrow!

**Comment by christopherdopp** [comment]
Thanks a lot (in advance) for designing these icons. 

I have a few ideas which you can ignore if you want-

* It would be nice if the waves animated slowly (maybe left to right?)
* The high tide icon could have the waves animating and slowly going up to indicate progressing towards high tide.
* Likewise the low tide icon could have the waves animating slowly down to indicate progressing towards low tide.

I'm sure whatever you create will be better than the static line drawings.

**Comment by basmilius** [comment]
So I've come up with the following, any feedback? 😄 

<table>
<tr>
<td><img alt="Tide High" src="https://raw.githubusercontent.com/basmilius/weather-icons/2.1/design/fill/animation-ready/tide-high.svg" width="128"/></td>
<td><img alt="Tide Low" src="https://raw.githubusercontent.com/basmilius/weather-icons/2.1/design/fill/animation-ready/tide-low.svg" width="128"/></td>
<td><img alt="Thermometer Water" src="https://raw.githubusercontent.com/basmilius/weather-icons/2.1/design/fill/animation-ready/thermometer-water.svg" width="128"/></td>
</tr>
</table>

**Comment by christopherdopp** [comment]
I think the icons you designed look great.

The only feedback I have is perhaps the speed of the vertical arrows is a bit too fast and draws more attention than other animated icons. Maybe slow the arrows down a bit? I'm not sure if the arrows should match the rising/falling of the waves or if it is better for them to be out of sync? Your call.

The other thought I have is maybe make the water level for the low tide icon a little lower (at the lowest point) ? I think that would emphasize the low tide more and make it easier to compare with the high tide icon.  

Other than those nitpicking suggestions, the icons look great. Thank you for taking the time to make them.

**Comment by basmilius** [comment]
Thanks for the feedback!

I agree that the arrow is animating too fast, it's now in line with other arrows, but maybe they're a bit to fast either. I'll look into that. The water in the low tide icon could be a bit lower, I'll change that too!

**Comment by basmilius** [comment]
I've updated them, sorry for the slight delay 😄 

**New**
<table>
<tr>
<td><img alt="Tide High" src="https://raw.githubusercontent.com/basmilius/weather-icons/2.1/production/fill/svg/tide-high.svg" width="128"/></td>
<td><img alt="Tide Low" src="https://raw.githubusercontent.com/basmilius/weather-icons/2.1/production/fill/svg/tide-low.svg" width="128"/></td>
<td><img alt="Thermometer Water" src="https://raw.githubusercontent.com/basmilius/weather-icons/2.1/production/fill/svg/thermometer-water.svg" width="128"/></td>
</tr>
</table>

**Old**
<table>
<tr>
<td><img alt="Tide High" src="https://raw.githubusercontent.com/basmilius/weather-icons/4adc5b741d8941db1e834b7eeedeb2ef5d661aa2/production/fill/svg/tide-high.svg" width="128"/></td>
<td><img alt="Tide Low" src="https://raw.githubusercontent.com/basmilius/weather-icons/4adc5b741d8941db1e834b7eeedeb2ef5d661aa2/production/fill/svg/tide-low.svg" width="128"/></td>
<td><img alt="Thermometer Water" src="https://raw.githubusercontent.com/basmilius/weather-icons/4adc5b741d8941db1e834b7eeedeb2ef5d661aa2/production/fill/svg/thermometer-water.svg" width="128"/></td>
</tr>
</table>

**Comment by christopherdopp** [comment]
The new versions are perfect. Thank you for spending the time to create and update them. I really appreciate it.

**Comment by christopherdopp** [comment]
I don't know if you want me to close this issue, but I have been using the animated icons and they look great.
Thanks.

**Comment by basmilius** [comment]
Thanks! I'll close this now :)
